const actionType = {
    DUMMY_FETCH : 'DUMMY_FETCH',
    REGISTER_STATUS: 'REGISTER_STATUS',
    REGISTER_ACCOUNTHOLDER_STATUS: 'REGISTER_ACCOUNTHOLDER_STATUS',
    LOGIN_STATUS: 'LOGIN_STATUS',
    TRANSFER_STATUS: 'TRANSFER_STATUS',
    WITHDRAW_DEPOSIT_STATUS: 'WITHDRAW_DEPOSIT_STATUS',
    ADD_PROFILE: 'ADD_PROFILE',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    JWT: 'JWT',
    ADD_CHECKINGS: 'ADD_CHECKINGS',
    ADD_A_CHECKING: 'ADD_A_CHECKING',
    UPDATE_CHECKINGS: 'UPDATE_CHECKINGS',
    ADD_SAVINGS: 'ADD_SAVINGS',
    ADD_A_SAVING: 'ADD_A_SAVING',
    UPDATE_SAVINGS: 'UPDATE_SAVINGSSAVINGS',
    ADD_CDS: 'ADD_CDS',
    UPDATE_CDS: 'UPDATE_CDS',
    LOG_OUT: 'LOG_OUT',
    SELECT_ACCOUNT: 'SELECT_ACCOUNT'
};

export default actionType;